default: &default
  :adapter: postgresql
  :encoding: unicode
  :host: 127.0.0.1
  :port: 5432
  :pool: 5

development:
  <<: *default
  :name: <%= ENV['DATABASE_NAME'] || 'santa_dev' %>

test:
  <<: *default
  :name: <%= ENV['DATABASE_TEST_NAME'] || 'santa_test' %>

